In [16]:
import pandas as pd

In [17]:
data_dep = pd.read_csv("../data/LGA_Flights_Departure.csv")
data_arr_no_dep = pd.read_csv("../data/LGA_Flights_Arrival_NoDep.csv")
data_arr = pd.read_csv("../data/LGA_Flights_Arrival_dep.csv")

In [18]:
data_dep.head()

,FlightDate,DepDelay,Distance,CRSDepTime,CRSElapsedTime,CRSArrTime,DayOfWeek,Year,Month,AverageDelayPerFlightNumber,...,Dest_PBI,Dest_PWM,Dest_RDU,Dest_RIC,Dest_RSW,Dest_SDF,Dest_SRQ,Dest_STL,Dest_TPA,Dest_TVC
0,2018-01-01,-2.0,762.0,479.0,75.0,394,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2018-01-01,-5.0,1076.0,1245.0,117.0,2,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2018-01-01,23.0,1076.0,1110.0,84.0,794,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
3,2018-01-01,-6.0,1076.0,895.0,118.0,693,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2018-01-01,-1.0,950.0,839.0,95.0,614,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
data_arr.head()

,FlightDate,DepTimeMinutes,TaxiOut,ArrDelay,Distance,CRSDepTime,CRSElapsedTime,CRSArrTime,DayOfWeek,Year,...,Origin_PBI,Origin_PWM,Origin_RIC,Origin_RSW,Origin_SDF,Origin_SRQ,Origin_STL,Origin_SYR,Origin_TPA,Origin_TVC
0,2018-01-01,516.0,14.0,-20.0,502.0,517.0,83.0,640,1,2018,...,0,0,0,0,0,0,0,0,0,0
1,2018-01-01,918.0,27.0,18.0,1076.0,926.0,143.0,1069,1,2018,...,0,0,0,0,0,0,0,0,0,0
2,2018-01-01,637.0,14.0,-25.0,950.0,640.0,111.0,791,1,2018,...,0,0,0,0,0,0,0,0,0,0
3,2018-01-01,986.0,13.0,36.0,950.0,970.0,116.0,1086,1,2018,...,0,0,0,0,0,0,0,0,0,0
4,2018-01-01,795.0,12.0,-22.0,1096.0,795.0,140.0,975,1,2018,...,0,0,0,0,0,0,0,0,0,0

In [20]:
data_arr_no_dep.head()

,FlightDate,ArrDelay,Distance,CRSDepTime,CRSElapsedTime,CRSArrTime,DayOfWeek,Year,Month,AverageDelayPerFlightNumber,...,GNV,HPN,TVC,RAP,PSC,JNU,SBN,GTF,BUR,LGB
0,2018-01-01,-20.0,502.0,640,83.0,640,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2018-01-01,18.0,1076.0,1069,143.0,1069,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2018-01-01,-25.0,950.0,791,111.0,791,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
3,2018-01-01,36.0,950.0,1086,116.0,1086,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2018-01-01,-22.0,1096.0,975,140.0,975,1,2018,1,0.0,...,0,0,0,0,0,0,0,0,0,0